apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: expense
  name: expense-trainee
rules: 
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  namespace: expense
  name: expense-trainee
roleRef: 
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: expense-trainee
subjects:
- apiGroup: rbac.authorization.k8s.io/v1
  kind: User
  name: VamsiB
